function RadioLangEN() {
    document.getElementById('radio-anom').innerHTML = 'SHORTWAVE RADIO'
    document.getElementById('ParaRabbitHole').innerHTML = 'I got into this rabbit hole just from watching YouTube videos on number stations, and in<br> one of the videos, they linked an online shortwave radio tuner. Naturally I checked it out, but I ended up<br> finding much stranger things(Atleast in my opinion.) Here is a collection of some of the weird shit i&apos;ve found.'
    document.getElementById('AudioDescFirst').innerHTML = 'This is what sounds like someone speaking saying English sentences, then repeating<br> it in Mandarin(Or the other way around, who knows?). It gets weirdly religous near the end for some reason, too.'
    document.getElementById('AudioDesc1').innerHTML = 'This sounds like two people speaking either Serbian or Russian, or some other slavic language.'
    document.getElementById('AudioDesc2').innerHTML = 'I don&apos;t know what the hell this is, sounds like some sort of data is being sent to someone.'
    document.getElementById('AudioDesc3').innerHTML = 'I ran into alot of weird-ass sounds and stations/signals when collecting the audio for this but <br>this one stands out to me for some reason.'
    document.getElementById('AudioDesc4').innerHTML = 'I&apos;ve also ran into stations that just send out what I think is morse code. I&apos;ve tried <br>cleaning these up and putting it through a translator but I only got gibberish.'
    document.getElementById('AudioDesc5').innerHTML = 'This is is actually in English(for the most part). What appears to be people speaking with the military alphabet.'
    document.getElementById('AudioDesc6').innerHTML = 'Just some random French station. Not sure why I recorded this in particular.'
    document.getElementById('AudioDesc7').innerHTML = 'Someone speaking in either Estionian, Finnish, or Greek. Not that special.'
    document.getElementById('AudioDesc8').innerHTML = 'This is is actually interesting because it (apparently) originates from the capital city of <br>North Korea: Pyongyang! It&apos;s a pretty weak transmission but you can still make out some music.'
    document.getElementById('AudioDesc9').innerHTML = 'Below is also some sort of signal. Again, it could be data but i&apos;m not sure.'
    document.getElementById('AudioDesc10').innerHTML = 'All of the stations from now on are just beeps. It may be morse code but some of them are too fast to be able to tell.'
}

function RadioLangDT() {
    document.getElementById('radio-anom').innerHTML = 'KORTEGOLF RADIO'
    document.getElementById('ParaRabbitHole').innerHTML = 'Ik kwam in dit konijnenhol terecht door het bekijken van YouTube-video&apos;s op nummerstations<br> en in een van de videos, koppelden ze een online kortegolfradiotuner. Natuurlijk heb ik het nagevraagd, maar ik ben uiteindelijk beland veel vreemde dingen vinden (naar mijn mening althans.) Hier is een verzameling van de rare dingen die ik heb gevonden.'
    document.getElementById('AudioDescFirst').innerHTML = 'Dit klinkt alsof iemand dingen in het Engels zegt en vervolgens herhaalt iemand anders ze in het Mandarijn (of omgekeerd, wie weet?). Om de een of andere reden wordt het aan het einde vreemd religieus.'
    document.getElementById('AudioDesc1').innerHTML = 'Dit klinkt als twee mensen die Servisch of Russisch spreken, of een andere slavische taal.'
    document.getElementById('AudioDesc2').innerHTML = 'Ik weet niet wat dit is, het klinkt alsof er een soort gegevens naar iemand wordt gestuurd.'
    document.getElementById('AudioDesc3').innerHTML = 'Ik kwam veel vreemde geluiden en stations / signalen tegen toen ik de audio hiervoor verzamelde, maar dit vind ik vreemd.'
    document.getElementById('AudioDesc4').innerHTML = 'Ik ben ook stations tegengekomen die alleen maar uitzenden wat volgens mij morse code is. Ik heb geprobeerd om ze op te ruimen en door een vertaler te halen, maar ik kreeg alleen wartaal.'
    document.getElementById('AudioDesc5').innerHTML = 'Dit is eigenlijk in het Engels (grotendeels). Wat lijkt te zijn mensen spreken met het militaire alfabet.'
    document.getElementById('AudioDesc6').innerHTML = 'Gewoon een willekeurig Frans station. Ik weet niet zeker waarom ik dit in het bijzonder heb opgenomen.'
    document.getElementById('AudioDesc7').innerHTML = 'Iemand die spreekt in het Ests, Fins of Grieks. Niet zo speciaal.'
    document.getElementById('AudioDesc8').innerHTML = 'Dit is eigenlijk interessant omdat het (blijkbaar) afkomstig is uit de hoofdstad of Noord-Korea: Pyongyang! Het is een vrij zwakke transmissie, maar je kunt nog steeds wat muziek maken.'
    document.getElementById('AudioDesc9').innerHTML = 'Hieronder is ook een soort signaal. Nogmaals, het kunnen gegevens zijn maar niet zeker.'
    document.getElementById('AudioDesc10').innerHTML = 'Alle zenders zijn vanaf nu slechts piepjes. Het kan morse code zijn maar sommige zijn te snel om te kunnen vertellen.'
}

function RadioLangJP() {
    document.getElementById('radio-anom').innerHTML = '短波ラジオ'
    document.getElementById('ParaRabbitHole').innerHTML = 'ナンバーステーションに関するYouTubeのビデオを見て、私はこのウサギの穴に入り、ビデオの1つに、オンラインの短波ラジオチューナーをリンクしました。 当然私はそれをチェックアウトしたが、私は私の意見では非常に奇妙なものを見つけることになった。 ここに私が見つけた奇妙なたわごとのコレクションがあります。'
    document.getElementById('AudioDescFirst').innerHTML = '誰かが英語の文章で何かを言うように聞こえますが、それはマンダリンでそれを繰り返す人のようです。 それはまた非常に宗教的な近端になるでしょう。' 
    document.getElementById('AudioDesc1').innerHTML = 'これは、セルビア語またはロシア語、または他のスラブ語を話す二人のように聞こえる。' 
    document.getElementById('AudioDesc2').innerHTML = '私はこの地獄が何であるか知りません。ある種のデータが誰かに送られているように聞こえます。' 
    document.getElementById('AudioDesc3').innerHTML = '' 
    document.getElementById('AudioDesc4').innerHTML = '' 
    document.getElementById('AudioDesc5').innerHTML = '' 
    document.getElementById('AudioDesc6').innerHTML = '' 
    document.getElementById('AudioDesc7').innerHTML = '' 
    document.getElementById('AudioDesc8').innerHTML = '' 
    document.getElementById('AudioDesc9').innerHTML =  ''
    document.getElementById('AudioDesc10').innerHTML =  ''
}

function RadioLangDK() {
    document.getElementById('radio-anom').innerHTML = 'KORTBØLGE RADIO'
    document.getElementById('ParaRabbitHole').innerHTML = 'Jeg kom ind i dette kaninhul fra at se YouTube-videoer på nummerstationer og i En af de videoer, de har tilsluttet en online shortwave radio tuner. Selvfølgelig kontrollerede jeg det, men jeg endte Find meget mærkelige ting (i hvert fald efter min mening). Her er en samling af nogle af de mærkelige lort jeg har fundet.'
    document.getElementById('AudioDescFirst').innerHTML = 'Det lyder som en person, der siger engelske sætninger og derefter gentager det i mandarin (eller omvendt, hvem ved det?). Det bliver underligt religiøst i slutningen af en eller anden grund.' 
    document.getElementById('AudioDesc1').innerHTML = '' 
    document.getElementById('AudioDesc2').innerHTML = '' 
    document.getElementById('AudioDesc3').innerHTML = '' 
    document.getElementById('AudioDesc4').innerHTML = '' 
    document.getElementById('AudioDesc5').innerHTML = '' 
    document.getElementById('AudioDesc6').innerHTML = '' 
    document.getElementById('AudioDesc7').innerHTML = '' 
    document.getElementById('AudioDesc8').innerHTML = '' 
    document.getElementById('AudioDesc9').innerHTML =  ''
    document.getElementById('AudioDesc10').innerHTML =  ''
}

function RadioLangVT() {
    document.getElementById('radio-anom').innerHTML = ''
    document.getElementById('ParaRabbitHole').innerHTML = ''
    document.getElementById('AudioDescFirst').innerHTML = '' 
    document.getElementById('AudioDesc1').innerHTML = '' 
    document.getElementById('AudioDesc2').innerHTML = '' 
    document.getElementById('AudioDesc3').innerHTML = '' 
    document.getElementById('AudioDesc4').innerHTML = '' 
    document.getElementById('AudioDesc5').innerHTML = '' 
    document.getElementById('AudioDesc6').innerHTML = '' 
    document.getElementById('AudioDesc7').innerHTML = '' 
    document.getElementById('AudioDesc8').innerHTML = '' 
    document.getElementById('AudioDesc9').innerHTML =  ''
    document.getElementById('AudioDesc10').innerHTML =  ''
}

function RadioLangFR() {
    document.getElementById('radio-anom').innerHTML = ''
    document.getElementById('ParaRabbitHole').innerHTML = ''
    document.getElementById('AudioDescFirst').innerHTML = '' 
    document.getElementById('AudioDesc1').innerHTML = '' 
    document.getElementById('AudioDesc2').innerHTML = '' 
    document.getElementById('AudioDesc3').innerHTML = '' 
    document.getElementById('AudioDesc4').innerHTML = '' 
    document.getElementById('AudioDesc5').innerHTML = '' 
    document.getElementById('AudioDesc6').innerHTML = '' 
    document.getElementById('AudioDesc7').innerHTML = '' 
    document.getElementById('AudioDesc8').innerHTML = '' 
    document.getElementById('AudioDesc9').innerHTML =  ''
    document.getElementById('AudioDesc10').innerHTML =  ''
}

function RadioLangKR() {
    document.getElementById('radio-anom').innerHTML = ''
    document.getElementById('ParaRabbitHole').innerHTML = ''
    document.getElementById('AudioDescFirst').innerHTML = '' 
    document.getElementById('AudioDesc1').innerHTML = '' 
    document.getElementById('AudioDesc2').innerHTML = '' 
    document.getElementById('AudioDesc3').innerHTML = '' 
    document.getElementById('AudioDesc4').innerHTML = '' 
    document.getElementById('AudioDesc5').innerHTML = '' 
    document.getElementById('AudioDesc6').innerHTML = '' 
    document.getElementById('AudioDesc7').innerHTML = '' 
    document.getElementById('AudioDesc8').innerHTML = '' 
    document.getElementById('AudioDesc9').innerHTML =  ''
    document.getElementById('AudioDesc10').innerHTML =  ''
}

function RadioLangSD() {
    document.getElementById('radio-anom').innerHTML = ''
    document.getElementById('ParaRabbitHole').innerHTML = ''
    document.getElementById('AudioDescFirst').innerHTML = 'Det låter som om någon säger något på engelska, då säger de det i Mandarin, det blir mycket religiöst nära slutet av någon anledning ...' 
    document.getElementById('AudioDesc1').innerHTML = '' 
    document.getElementById('AudioDesc2').innerHTML = '' 
    document.getElementById('AudioDesc3').innerHTML = '' 
    document.getElementById('AudioDesc4').innerHTML = '' 
    document.getElementById('AudioDesc5').innerHTML = '' 
    document.getElementById('AudioDesc6').innerHTML = '' 
    document.getElementById('AudioDesc7').innerHTML = '' 
    document.getElementById('AudioDesc8').innerHTML = '' 
    document.getElementById('AudioDesc9').innerHTML =  ''
    document.getElementById('AudioDesc10').innerHTML =  ''
}

function RadioLangPL() {
    document.getElementById('radio-anom').innerHTML = ''
    document.getElementById('ParaRabbitHole').innerHTML = ''
    document.getElementById('AudioDescFirst').innerHTML = '' 
    document.getElementById('AudioDesc1').innerHTML = '' 
    document.getElementById('AudioDesc2').innerHTML = '' 
    document.getElementById('AudioDesc3').innerHTML = '' 
    document.getElementById('AudioDesc4').innerHTML = '' 
    document.getElementById('AudioDesc5').innerHTML = '' 
    document.getElementById('AudioDesc6').innerHTML = '' 
    document.getElementById('AudioDesc7').innerHTML = '' 
    document.getElementById('AudioDesc8').innerHTML = '' 
    document.getElementById('AudioDesc9').innerHTML =  ''
    document.getElementById('AudioDesc10').innerHTML =  ''
}

function RadioLangRS() {
    document.getElementById('radio-anom').innerHTML = ''
    document.getElementById('ParaRabbitHole').innerHTML = ''
    document.getElementById('AudioDescFirst').innerHTML = '' 
    document.getElementById('AudioDesc1').innerHTML = '' 
    document.getElementById('AudioDesc2').innerHTML = '' 
    document.getElementById('AudioDesc3').innerHTML = '' 
    document.getElementById('AudioDesc4').innerHTML = '' 
    document.getElementById('AudioDesc5').innerHTML = '' 
    document.getElementById('AudioDesc6').innerHTML = '' 
    document.getElementById('AudioDesc7').innerHTML = '' 
    document.getElementById('AudioDesc8').innerHTML = '' 
    document.getElementById('AudioDesc9').innerHTML =  ''
    document.getElementById('AudioDesc10').innerHTML =  ''
}

function RadioLangIT() {
    document.getElementById('radio-anom').innerHTML = ''
    document.getElementById('ParaRabbitHole').innerHTML = ''
    document.getElementById('AudioDescFirst').innerHTML = '' 
    document.getElementById('AudioDesc1').innerHTML = '' 
    document.getElementById('AudioDesc2').innerHTML = '' 
    document.getElementById('AudioDesc3').innerHTML = '' 
    document.getElementById('AudioDesc4').innerHTML = '' 
    document.getElementById('AudioDesc5').innerHTML = '' 
    document.getElementById('AudioDesc6').innerHTML = '' 
    document.getElementById('AudioDesc7').innerHTML = '' 
    document.getElementById('AudioDesc8').innerHTML = '' 
    document.getElementById('AudioDesc9').innerHTML =  ''
    document.getElementById('AudioDesc10').innerHTML =  ''
}

function RadioLangSP() {
    document.getElementById('radio-anom').innerHTML = ''
    document.getElementById('ParaRabbitHole').innerHTML = ''
    document.getElementById('AudioDescFirst').innerHTML = '' 
    document.getElementById('AudioDesc1').innerHTML = '' 
    document.getElementById('AudioDesc2').innerHTML = '' 
    document.getElementById('AudioDesc3').innerHTML = '' 
    document.getElementById('AudioDesc4').innerHTML = '' 
    document.getElementById('AudioDesc5').innerHTML = '' 
    document.getElementById('AudioDesc6').innerHTML = '' 
    document.getElementById('AudioDesc7').innerHTML = '' 
    document.getElementById('AudioDesc8').innerHTML = '' 
    document.getElementById('AudioDesc9').innerHTML =  ''
    document.getElementById('AudioDesc10').innerHTML =  ''
}

function RadioLangGR() {
    document.getElementById('radio-anom').innerHTML = ''
    document.getElementById('ParaRabbitHole').innerHTML = ''
    document.getElementById('AudioDescFirst').innerHTML = '' 
    document.getElementById('AudioDesc1').innerHTML = '' 
    document.getElementById('AudioDesc2').innerHTML = '' 
    document.getElementById('AudioDesc3').innerHTML = '' 
    document.getElementById('AudioDesc4').innerHTML = '' 
    document.getElementById('AudioDesc5').innerHTML = '' 
    document.getElementById('AudioDesc6').innerHTML = '' 
    document.getElementById('AudioDesc7').innerHTML = '' 
    document.getElementById('AudioDesc8').innerHTML = '' 
    document.getElementById('AudioDesc9').innerHTML =  ''
    document.getElementById('AudioDesc10').innerHTML =  ''
}

function RadioLangCH() {
    document.getElementById('radio-anom').innerHTML = ''
    document.getElementById('ParaRabbitHole').innerHTML = ''
    document.getElementById('AudioDescFirst').innerHTML = '' 
    document.getElementById('AudioDesc1').innerHTML = '' 
    document.getElementById('AudioDesc2').innerHTML = '' 
    document.getElementById('AudioDesc3').innerHTML = '' 
    document.getElementById('AudioDesc4').innerHTML = '' 
    document.getElementById('AudioDesc5').innerHTML = '' 
    document.getElementById('AudioDesc6').innerHTML = '' 
    document.getElementById('AudioDesc7').innerHTML = '' 
    document.getElementById('AudioDesc8').innerHTML = '' 
    document.getElementById('AudioDesc9').innerHTML =  ''
    document.getElementById('AudioDesc10').innerHTML =  ''
}

function RadioLangFN() {
    document.getElementById('radio-anom').innerHTML = ''
    document.getElementById('ParaRabbitHole').innerHTML = ''
    document.getElementById('AudioDescFirst').innerHTML = '' 
    document.getElementById('AudioDesc1').innerHTML = '' 
    document.getElementById('AudioDesc2').innerHTML = '' 
    document.getElementById('AudioDesc3').innerHTML = '' 
    document.getElementById('AudioDesc4').innerHTML = '' 
    document.getElementById('AudioDesc5').innerHTML = '' 
    document.getElementById('AudioDesc6').innerHTML = '' 
    document.getElementById('AudioDesc7').innerHTML = '' 
    document.getElementById('AudioDesc8').innerHTML = '' 
    document.getElementById('AudioDesc9').innerHTML =  ''
    document.getElementById('AudioDesc10').innerHTML =  ''
}

function RadioLangGK() {
    document.getElementById('radio-anom').innerHTML = ''
    document.getElementById('ParaRabbitHole').innerHTML = ''
    document.getElementById('AudioDescFirst').innerHTML = '' 
    document.getElementById('AudioDesc1').innerHTML = '' 
    document.getElementById('AudioDesc2').innerHTML = '' 
    document.getElementById('AudioDesc3').innerHTML = '' 
    document.getElementById('AudioDesc4').innerHTML = '' 
    document.getElementById('AudioDesc5').innerHTML = '' 
    document.getElementById('AudioDesc6').innerHTML = '' 
    document.getElementById('AudioDesc7').innerHTML = '' 
    document.getElementById('AudioDesc8').innerHTML = '' 
    document.getElementById('AudioDesc9').innerHTML =  ''
    document.getElementById('AudioDesc10').innerHTML =  ''
}

function RadioLangPT() {
    document.getElementById('radio-anom').innerHTML = ''
    document.getElementById('ParaRabbitHole').innerHTML = ''
    document.getElementById('AudioDescFirst').innerHTML = '' 
    document.getElementById('AudioDesc1').innerHTML = '' 
    document.getElementById('AudioDesc2').innerHTML = '' 
    document.getElementById('AudioDesc3').innerHTML = '' 
    document.getElementById('AudioDesc4').innerHTML = '' 
    document.getElementById('AudioDesc5').innerHTML = '' 
    document.getElementById('AudioDesc6').innerHTML = '' 
    document.getElementById('AudioDesc7').innerHTML = '' 
    document.getElementById('AudioDesc8').innerHTML = '' 
    document.getElementById('AudioDesc9').innerHTML =  ''
    document.getElementById('AudioDesc10').innerHTML =  ''
}

function RadioLangEE() {
    document.getElementById('radio-anom').innerHTML = ''
    document.getElementById('ParaRabbitHole').innerHTML = ''
    document.getElementById('AudioDescFirst').innerHTML = '' 
    document.getElementById('AudioDesc1').innerHTML = '' 
    document.getElementById('AudioDesc2').innerHTML = '' 
    document.getElementById('AudioDesc3').innerHTML = '' 
    document.getElementById('AudioDesc4').innerHTML = '' 
    document.getElementById('AudioDesc5').innerHTML = '' 
    document.getElementById('AudioDesc6').innerHTML = '' 
    document.getElementById('AudioDesc7').innerHTML = '' 
    document.getElementById('AudioDesc8').innerHTML = '' 
    document.getElementById('AudioDesc9').innerHTML =  ''
    document.getElementById('AudioDesc10').innerHTML =  ''
}

function RadioLangIS() {
    document.getElementById('radio-anom').innerHTML = ''
    document.getElementById('ParaRabbitHole').innerHTML = ''
    document.getElementById('AudioDescFirst').innerHTML = '' 
    document.getElementById('AudioDesc1').innerHTML = '' 
    document.getElementById('AudioDesc2').innerHTML = '' 
    document.getElementById('AudioDesc3').innerHTML = '' 
    document.getElementById('AudioDesc4').innerHTML = '' 
    document.getElementById('AudioDesc5').innerHTML = '' 
    document.getElementById('AudioDesc6').innerHTML = '' 
    document.getElementById('AudioDesc7').innerHTML = '' 
    document.getElementById('AudioDesc8').innerHTML = '' 
    document.getElementById('AudioDesc9').innerHTML =  ''
    document.getElementById('AudioDesc10').innerHTML =  ''
}

function RadioLangID() {
    document.getElementById('radio-anom').innerHTML = ''
    document.getElementById('ParaRabbitHole').innerHTML = ''
    document.getElementById('AudioDescFirst').innerHTML = '' 
    document.getElementById('AudioDesc1').innerHTML = '' 
    document.getElementById('AudioDesc2').innerHTML = '' 
    document.getElementById('AudioDesc3').innerHTML = '' 
    document.getElementById('AudioDesc4').innerHTML = '' 
    document.getElementById('AudioDesc5').innerHTML = '' 
    document.getElementById('AudioDesc6').innerHTML = '' 
    document.getElementById('AudioDesc7').innerHTML = '' 
    document.getElementById('AudioDesc8').innerHTML = '' 
    document.getElementById('AudioDesc9').innerHTML =  ''
    document.getElementById('AudioDesc10').innerHTML =  ''
}

